apiVersion: apps/v1 
kind: Deployment
metadata:
  name: valaxy-regapp
  labels: 
     app: regapp
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      imagePullSecrets:
      - name: "dockerhub"
      containers:
      - name: regapp
        image: mzm1/devopjava:35
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: '1'
            memory: '500Mi'
          requests:
            cpu: '1'
            memory: '500Mi'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 5000
      targetPort: 5000

  type: LoadBalancer

